/*
	Personal Project SQL Script
    Daniel Eum
*/

-- Use my database
USE km_eumdaniel;

/*
	Drop Tables so the database starts fresh
*/


DELIMITER $$
DROP PROCEDURE IF EXISTS SP_DROP_TABLES$$
CREATE PROCEDURE SP_DROP_TABLES()
BEGIN

DROP TABLE IF EXISTS PLAYERCARDS;
DROP TABLE IF EXISTS PLAYERPOSITIONS;
DROP TABLE IF EXISTS PLAYERSEASON;
DROP TABLE IF EXISTS PLAYERAWARD;

DROP TABLE IF EXISTS PLAYER_HISTORY;
DROP TABLE IF EXISTS AWARD;
DROP TABLE IF EXISTS SEASON;
DROP TABLE IF EXISTS POSITIONS;
DROP TABLE IF EXISTS CARDS;
DROP TABLE IF EXISTS STATS;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS TRANSFERLIST;

END $$

DELIMITER ;

/*
	Create Tables
*/

DELIMITER $$
DROP PROCEDURE IF EXISTS SP_CREATE_TABLES$$
CREATE PROCEDURE SP_CREATE_TABLES()
BEGIN

-- Create the AWARD Table
CREATE TABLE IF NOT EXISTS AWARD (
AWARD_ID INT AUTO_INCREMENT PRIMARY KEY,
AWARD_TITLE VARCHAR(50)
);

-- Create the SEASON Table
CREATE TABLE IF NOT EXISTS SEASON (
SEASON_ID INT AUTO_INCREMENT PRIMARY KEY,
SEASON_YEAR INT NOT NULL CHECK(SEASON_YEAR >= 2018) 
);

-- Create the POSITIONS Table
CREATE TABLE IF NOT EXISTS POSITIONS (
POSITIONS_ID INT AUTO_INCREMENT PRIMARY KEY,
POSITIONS_PRIMARY VARCHAR(30) NOT NULL
);


-- Create the COUNTRY Table
CREATE TABLE IF NOT EXISTS COUNTRY (
COUNTRY_ID INT AUTO_INCREMENT PRIMARY KEY,
COUNTRY_NAME VARCHAR(50) NOT NULL
);

-- Create the TRANSFERLIST Table
CREATE TABLE IF NOT EXISTS TRANSFERLIST (
TRANSFERLIST_ID INT AUTO_INCREMENT PRIMARY KEY,
TRANSFERLIST_LISTED BOOLEAN NOT NULL
);

-- Create the PLAYER Table
CREATE TABLE IF NOT EXISTS PLAYER (
PLAYER_ID INT AUTO_INCREMENT PRIMARY KEY,
COUNTRY_ID INT,
TRANSFERLIST_ID INT, 
PLAYER_FIRST_NAME VARCHAR(50) NOT NULL,
PLAYER_LAST_NAME VARCHAR(50) NOT NULL,
PLAYER_AGE INT NOT NULL 
	CHECK(PLAYER_AGE >= 16 AND PLAYER_AGE <= 40),
PLAYER_WEIGHT INT NOT NULL 
	CHECK(PLAYER_WEIGHT >= 120 AND PLAYER_WEIGHT <= 230),
PLAYER_HEIGHT INT NOT NULL 
	CHECK(PLAYER_HEIGHT >= 150 AND PLAYER_HEIGHT <= 230),
PLAYER_JERSEY_NUMBER INT NOT NULL 
	CHECK(PLAYER_JERSEY_NUMBER >= 0),
PLAYER_MARKET_VALUE INT NOT NULL 
	CHECK(PLAYER_MARKET_VALUE > 0),
PLAYER_WAGE INT NOT NULL 
	CHECK(PLAYER_WAGE > 0),
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID),
FOREIGN KEY (TRANSFERLIST_ID) REFERENCES TRANSFERLIST (TRANSFERLIST_ID)
);

-- Create the STATS Table
CREATE TABLE IF NOT EXISTS STATS (
STATS_ID INT AUTO_INCREMENT PRIMARY KEY,
STATS_GOAL_SCORED INT NOT NULL 
	CHECK(STATS_GOAL_SCORED >= 0),
STATS_GOAL_ASSISTED INT NOT NULL 
	CHECK(STATS_GOAL_ASSISTED >= 0),
STATS_CLEAN_SHEET INT 
	CHECK(STATS_CLEAN_SHEET >= 0),
STATS_GAMES_PLAYED INT NOT NULL 
	CHECK(STATS_GAMES_PLAYED >= 0)
);

-- Create the PLAYER_HISTORY Table
CREATE TABLE IF NOT EXISTS PLAYER_HISTORY (
PLAYER_HISTORY_START_YEAR INT,
PLAYER_ID INT,
PLAYER_HISTORY_END_YEAR INT,
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
PRIMARY KEY (PLAYER_HISTORY_START_YEAR, PLAYER_ID)
);

-- Create the PLAYERPOSITION Table
CREATE TABLE IF NOT EXISTS PLAYERPOSITIONS (
PLAYER_ID INT,
POSITIONS_ID INT,
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
FOREIGN KEY (POSITIONS_ID) REFERENCES POSITIONS(POSITIONS_ID),
PRIMARY KEY (PLAYER_ID, POSITIONS_ID)
);

-- Create the PLAYERSEASON Table
CREATE TABLE IF NOT EXISTS PLAYERSEASON (
SEASON_ID INT,
PLAYER_ID INT,
STATS_ID INT,
FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
FOREIGN KEY (STATS_ID) REFERENCES STATS(STATS_ID),
PRIMARY KEY (SEASON_ID, PLAYER_ID)
);

-- Create the PLAYERAWARD Table
CREATE TABLE IF NOT EXISTS PLAYERAWARD (
PLAYER_ID INT,
AWARD_ID INT,
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
FOREIGN KEY (AWARD_ID) REFERENCES AWARD(AWARD_ID),
PRIMARY KEY (PLAYER_ID, AWARD_ID)
);

END $$

DELIMITER ;

/*
	Stored Procedures
*/


DELIMITER $$

-- Create/Replace a Proceudure called SP_COUNTRY_ADD that adds a country if it does not exist
DROP PROCEDURE IF EXISTS SP_COUNTRY_ADD$$
CREATE PROCEDURE SP_COUNTRY_ADD (IN C_NAME VARCHAR(50)) 
BEGIN
	INSERT INTO COUNTRY(COUNTRY_NAME)
	SELECT C_NAME
	WHERE 
		NOT EXISTS (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = C_NAME);
END$$

-- Create/Replace a Proceudure called SP_POSITIONS_ADD that adds a position if it does not exist
DROP PROCEDURE IF EXISTS SP_POSITIONS_ADD$$
CREATE PROCEDURE SP_POSITIONS_ADD (IN P_PRIMARY VARCHAR(30)) 
BEGIN
	INSERT INTO POSITIONS(POSITIONS_PRIMARY)
	SELECT P_PRIMARY
	WHERE 
		NOT EXISTS (SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = P_PRIMARY);
END$$

-- Create/Replace a Proceudure called SP_TRANSFERLIST_ADD that adds a transfer list status if it does not exist
DROP PROCEDURE IF EXISTS SP_TRANSFERLIST_ADD$$
CREATE PROCEDURE SP_TRANSFERLIST_ADD (IN T_LISTED BOOLEAN) 
BEGIN
	INSERT INTO TRANSFERLIST(TRANSFERLIST_LISTED)
	SELECT T_LISTED
	WHERE 
		NOT EXISTS (SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED = T_LISTED);
END$$

-- Create/Replace a Proceudure called SP_AWARD_ADD that adds an Award if it does not exist
DROP PROCEDURE IF EXISTS SP_AWARD_ADD$$
CREATE PROCEDURE SP_AWARD_ADD (IN A_TITLE VARCHAR(50)) 
BEGIN
	INSERT INTO AWARD(AWARD_TITLE)
	SELECT A_TITLE
	WHERE 
		NOT EXISTS (SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = A_TITLE);
END$$

-- Create/Replace a Proceudure called SP_PLAYER_ADD that adds a Player if it does not exist
DROP PROCEDURE IF EXISTS SP_PLAYER_ADD$$
CREATE PROCEDURE SP_PLAYER_ADD (IN T_ID INT, IN C_ID INT, IN P_FIRST VARCHAR(50), IN P_LAST VARCHAR(50),
								IN P_MARKET_VALUE INT, IN P_WAGE INT, IN P_AGE INT, IN P_HEIGHT INT,
                                IN P_WEIGHT INT, IN P_JERSEY_NUMBER INT) 
BEGIN
	INSERT INTO PLAYER(TRANSFERLIST_ID, COUNTRY_ID, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_MARKET_VALUE, PLAYER_WAGE, 
					PLAYER_AGE, PLAYER_HEIGHT, PLAYER_WEIGHT, PLAYER_JERSEY_NUMBER)
	SELECT T_ID, C_ID, P_FIRST, P_LAST, P_MARKET_VALUE, P_WAGE, P_AGE, P_HEIGHT, P_WEIGHT, P_JERSEY_NUMBER
	WHERE 
		NOT EXISTS (SELECT PLAYER_ID FROM PLAYER WHERE TRANSFERLIST_ID = T_ID AND COUNTRY_ID = C_ID AND
					PLAYER_FIRST_NAME = P_FIRST AND PLAYER_LAST_NAME = P_LAST AND PLAYER_MARKET_VALUE = P_MARKET_VALUE
                    AND PLAYER_WAGE = P_WAGE AND PLAYER_AGE = P_AGE AND PLAYER_HEIGHT = P_HEIGHT AND PLAYER_WEIGHT = P_WEIGHT
                    AND PLAYER_JERSEY_NUMBER = P_JERSEY_NUMBER);
END$$

-- Create/Replace a Proceudure called SP_PLAYERAWARD_ADD that adds an PLAYERAWARD if it does not exist
DROP PROCEDURE IF EXISTS SP_PLAYERAWARD_ADD$$
CREATE PROCEDURE SP_PLAYERAWARD_ADD (IN P_ID INT, IN A_ID INT) 
BEGIN
	INSERT INTO PLAYERAWARD(PLAYER_ID, AWARD_ID)
	SELECT P_ID, A_ID;
END$$

-- Create/Replace a Proceudure called SP_PLAYERPOSITIONS_ADD that adds a PLAYERPOSITIONS if it does not exist
DROP PROCEDURE IF EXISTS SP_PLAYERPOSITIONS_ADD$$
CREATE PROCEDURE SP_PLAYERPOSITIONS_ADD (IN P_ID INT, IN POSI_ID INT) 
BEGIN
	INSERT INTO PLAYERPOSITIONS(PLAYER_ID, POSITIONS_ID)
	SELECT P_ID, POSI_ID
    WHERE 
		NOT EXISTS (SELECT PLAYER_ID FROM PLAYERPOSITIONS WHERE PLAYER_ID = P_ID);
END$$

-- Create/Replace a Proceudure called SP_SEASON_ADD that adds a Season if it does not exist
DROP PROCEDURE IF EXISTS SP_SEASON_ADD$$
CREATE PROCEDURE SP_SEASON_ADD (IN S_YEAR INT) 
BEGIN
	INSERT INTO SEASON(SEASON_YEAR)
	SELECT S_YEAR
    WHERE 
		NOT EXISTS (SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = S_YEAR);
END$$

-- Create/Replace a Proceudure called SP_STATS_ADD that adds a Stats if it does not exist
DROP PROCEDURE IF EXISTS SP_STATS_ADD$$
CREATE PROCEDURE SP_STATS_ADD (IN S_GOAL INT, IN S_ASSISTED INT, IN S_CLEAN INT, IN S_GAMES INT) 
BEGIN
	INSERT INTO STATS(STATS_GOAL_SCORED, STATS_GOAL_ASSISTED, STATS_CLEAN_SHEET, STATS_GAMES_PLAYED)
	SELECT S_GOAL, S_ASSISTED, S_CLEAN, S_GAMES;
END$$

-- Create/Replace a Procedure called SP_PLAYERSEASON_ADD that adds a PLAYERSEASON if it does not exist
DROP PROCEDURE IF EXISTS SP_PLAYERSEASON_ADD$$
CREATE PROCEDURE SP_PLAYERSEASON_ADD (IN S_ID INT, IN P_ID INT, IN ST_ID INT)
BEGIN
	INSERT INTO PLAYERSEASON(SEASON_ID,PLAYER_ID,STATS_ID)
    SELECT S_ID, P_ID, ST_ID;
END$$

-- Create/Replace a Procedure called SP_PLAYERHISTORY_ADD that adds a PLAYER_HISTORY if it does not exist
DROP PROCEDURE IF EXISTS SP_PLAYERHISTORY_ADD$$
CREATE PROCEDURE SP_PLAYERHISTORY_ADD (IN P_START_YEAR INT, IN P_ID INT, IN P_END_YEAR INT)
BEGIN
	INSERT INTO PLAYER_HISTORY(PLAYER_HISTORY_START_YEAR,PLAYER_ID,PLAYER_HISTORY_END_YEAR)
    SELECT P_START_YEAR, P_ID, P_END_YEAR;
END$$

DELIMITER ;

/*
	Add Data to the tables
*/

DELIMITER $$
DROP PROCEDURE IF EXISTS SP_POPULATE_DATA$$
CREATE PROCEDURE SP_POPULATE_DATA()
BEGIN
    
-- Add data to COUNTRY Table 
CALL SP_COUNTRY_ADD('England');
CALL SP_COUNTRY_ADD('Portugal');
CALL SP_COUNTRY_ADD('Spain');
CALL SP_COUNTRY_ADD('Argentina');
CALL SP_COUNTRY_ADD('Sweden');
CALL SP_COUNTRY_ADD('Ivory Coast');
CALL SP_COUNTRY_ADD('Brazil');
CALL SP_COUNTRY_ADD('France');
CALL SP_COUNTRY_ADD('Wales');
CALL SP_COUNTRY_ADD('Uruguay');
CALL SP_COUNTRY_ADD('Netherlands');
CALL SP_COUNTRY_ADD('Serbia');
CALL SP_COUNTRY_ADD('Scotland');
    
-- Add data to POSITIONS Table
CALL SP_POSITIONS_ADD('Goalkeeper');
CALL SP_POSITIONS_ADD('Center Back');
CALL SP_POSITIONS_ADD('Right Back');
CALL SP_POSITIONS_ADD('Left Back');
CALL SP_POSITIONS_ADD('Right Wing');
CALL SP_POSITIONS_ADD('Center Midfield');
CALL SP_POSITIONS_ADD('Left Wing');
CALL SP_POSITIONS_ADD('Striker');
    
-- Add data to the TRANSFERLIST 
CALL SP_TRANSFERLIST_ADD(TRUE);
CALL SP_TRANSFERLIST_ADD(FALSE);

-- Add data to the AWARD 
CALL SP_AWARD_ADD('Premier League Player of the Year');
CALL SP_AWARD_ADD('Manchester United Player of the Year');
CALL SP_AWARD_ADD('Premier League top 11 Player of the Year');
CALL SP_AWARD_ADD('Premier League Golden Boot');
CALL SP_AWARD_ADD('Young Player of the Year');
CALL SP_AWARD_ADD('Come Back Player of the Year');
CALL SP_AWARD_ADD('Ballon dOr');
CALL SP_AWARD_ADD(NULL);

-- Add data to the PLAYER 
-- Used Subquery to find TRANSFERLIST_ID AND COUNTRY_ID
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS TRUE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Spain'), 'Juan', 'Mata', 6, 8, 33, 170, 134, 8);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Spain'), 'David', 'DeGea', 50, 14, 30, 190, 181, 1);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Dean', 'Henderson', 22, 5, 24, 188, 187, 26);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS TRUE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'France'), 'Anthony', 'Martial', 42, 9, 25, 176, 168, 9);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Luke', 'Shaw', 35, 10, 25, 184, 168, 23);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Marcus', 'Rashford', 110, 11, 23, 177, 152, 10);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS TRUE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Argentina'), 'Sergio', 'Romero', 10, 6, 34, 190, 192, 22);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS TRUE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Phil', 'Jones', 6, 6, 29, 178, 157, 4);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'France'), 'Paul', 'Pogba', 65, 13, 28, 188, 183, 6);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Ivory Coast'), 'Eric', 'Baily', 15, 8, 27, 188, 170, 3);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Serbia'), 'Nemanja', 'Matic', 12, 9, 32, 191, 185, 31);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Scotland'), 'Scott', 'McTominay', 30, 9, 24, 188, 192, 34);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Sweden'), 'Victor', 'Lindelof', 33, 9, 26, 187, 174, 2);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Brazil'), 'Fred', 'Santos', 30, 7, 28, 175, 139, 17);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Mason', 'Greenwood', 60, 8, 19, 179, 152, 11);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Aaron', 'Wan-Bissaka', 40, 9, 23, 182, 159, 29);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Harry', 'Maguire', 50, 12, 29, 193, 210, 5);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS TRUE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Wales'), 'Daniel', 'James', 20, 5, 23, 174, 168, 21);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Portugal'), 'Bruno', 'Fernandes', 90, 13, 26, 179, 150, 18);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Uruguay'), 'Edinson', 'Cavani', 13, 8, 34, 182, 157, 7);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE),
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'England'), 'Brandon', 'Williams', 10, 5, 20, 177, 140, 33);
CALL SP_PLAYER_ADD((SELECT TRANSFERLIST_ID FROM TRANSFERLIST WHERE TRANSFERLIST_LISTED IS FALSE), 
     (SELECT COUNTRY_ID FROM COUNTRY WHERE COUNTRY_NAME = 'Brazil'), 'Alex', 'Telles', 30, 7, 28, 178, 157, 27);
    
-- Add data to PLAYERAWARD
CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Come Back Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Young Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Young Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Manchester United Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE = 'Premier League top 11 Player of the Year'));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));
                        
CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));
                        
CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

CALL SP_PLAYERAWARD_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'),
						(SELECT AWARD_ID FROM AWARD WHERE AWARD_TITLE IS NULL));

-- Add data to PLAYERPOSITIONS

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Right Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Goalkeeper'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Striker'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Left Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Striker'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Right Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Midfield'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Left Wing'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Right Wing'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Goalkeeper'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Left Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Back'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Left Wing'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Goalkeeper'));

CALL SP_PLAYERPOSITIONS_ADD((SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'),
							(SELECT POSITIONS_ID FROM POSITIONS WHERE POSITIONS_PRIMARY = 'Center Back'));

-- Add data to the SEASON 
CALL SP_SEASON_ADD(2018);
CALL SP_SEASON_ADD(2019);
CALL SP_SEASON_ADD(2020);

-- Add data to the STATS for 2018 Season
CALL SP_STATS_ADD(3,2,NULL,22);
CALL SP_STATS_ADD(1,0,NULL,28);
CALL SP_STATS_ADD(2,0,NULL,16);
CALL SP_STATS_ADD(1,1,6,30);
CALL SP_STATS_ADD(10,2,NULL,27);
CALL SP_STATS_ADD(1,1,NULL,17);
CALL SP_STATS_ADD(1,4,6,29);
CALL SP_STATS_ADD(13,9,NULL,35);
CALL SP_STATS_ADD(10,6,NULL,33);
CALL SP_STATS_ADD(0,0,NULL,3);
CALL SP_STATS_ADD(0,0,0,0);
CALL SP_STATS_ADD(0,0,7,38);
CALL SP_STATS_ADD(0,1,3,18);
CALL SP_STATS_ADD(0,0,1,12);
    
-- Add data to the STATS for 2019 Season
CALL SP_STATS_ADD(0,2,NULL,19);
CALL SP_STATS_ADD(0,2,NULL,21);
CALL SP_STATS_ADD(4,1,NULL,27);
CALL SP_STATS_ADD(1,0,12,35);
CALL SP_STATS_ADD(0,4,11,35);
CALL SP_STATS_ADD(17,6,NULL,32);
CALL SP_STATS_ADD(0,0,NULL,29);
CALL SP_STATS_ADD(0,0,7,24);
CALL SP_STATS_ADD(1,3,NULL,16);
CALL SP_STATS_ADD(17,7,NULL,31);
CALL SP_STATS_ADD(10,1,NULL,31);
CALL SP_STATS_ADD(0,0,13,38);
CALL SP_STATS_ADD(0,0,0,2);
CALL SP_STATS_ADD(1,1,13,38);
CALL SP_STATS_ADD(0,0,1,4);
CALL SP_STATS_ADD(3,6,NULL,33);
    
-- Add data to the STATS for 2020 Season
CALL SP_STATS_ADD(18,11,NULL,36);
CALL SP_STATS_ADD(0,2,NULL,8);
CALL SP_STATS_ADD(0,0,NULL,19);
CALL SP_STATS_ADD(4,1,NULL,31);
CALL SP_STATS_ADD(1,1,10,28);
CALL SP_STATS_ADD(2,4,13,33);
CALL SP_STATS_ADD(0,0,4,12);
CALL SP_STATS_ADD(4,3,NULL,22);
CALL SP_STATS_ADD(1,0,NULL,29);
CALL SP_STATS_ADD(1,5,10,31);
CALL SP_STATS_ADD(9,3,NULL,25);
CALL SP_STATS_ADD(0,0,0,3);
CALL SP_STATS_ADD(3,3,NULL,25);
CALL SP_STATS_ADD(11,9,NULL,36);
CALL SP_STATS_ADD(7,2,NULL,30);
CALL SP_STATS_ADD(0,0,9,25);
CALL SP_STATS_ADD(2,1,13,34);
CALL SP_STATS_ADD(0,2,1,8);
CALL SP_STATS_ADD(0,0,3,11);
CALL SP_STATS_ADD(3,0,NULL,14);

-- Add data to the PLAYERSEASON

-- 2018 Season
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 3 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 22));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 28));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 2 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 16));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET = 6 AND STATS_GAMES_PLAYED = 30));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 10 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 27));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 17));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 4 AND STATS_CLEAN_SHEET = 6 AND STATS_GAMES_PLAYED = 29));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 13 
                        AND STATS_GOAL_ASSISTED = 9 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 35));  
 
 CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 10 
                        AND STATS_GOAL_ASSISTED = 6 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 33));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 3));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 0));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
					(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
					(SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
					AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 7 AND STATS_GAMES_PLAYED = 38));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET = 3 AND STATS_GAMES_PLAYED = 18));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 1 AND STATS_GAMES_PLAYED = 12));  


CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'), NULL);

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'), NULL);

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2018),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'), NULL);
   

-- 2019 Season
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 19));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 21));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 4 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 27));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 12 AND STATS_GAMES_PLAYED = 35));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 4 AND STATS_CLEAN_SHEET = 11 AND STATS_GAMES_PLAYED = 35));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 17 
                        AND STATS_GOAL_ASSISTED = 6 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 32));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 29));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 7 AND STATS_GAMES_PLAYED = 24));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 3 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 16));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 17 
                        AND STATS_GOAL_ASSISTED = 7 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 31));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 10 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 31));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 0));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 13 AND STATS_GAMES_PLAYED = 38));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 2));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET = 13 AND STATS_GAMES_PLAYED = 38));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 1 AND STATS_GAMES_PLAYED = 4));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 3 
                        AND STATS_GOAL_ASSISTED = 6 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 33));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'), NULL); 

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'), NULL);
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'), NULL); 
    
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2019),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'), NULL); 
    
-- 2020 Season
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 18 
                        AND STATS_GOAL_ASSISTED = 11 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 36));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 8));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 19));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 4 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 31));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET = 10 AND STATS_GAMES_PLAYED = 28));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 2 
                        AND STATS_GOAL_ASSISTED = 4 AND STATS_CLEAN_SHEET = 13 AND STATS_GAMES_PLAYED = 33));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 4 AND STATS_GAMES_PLAYED = 12));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 4 
                        AND STATS_GOAL_ASSISTED = 3 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 22));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 29));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 1 
                        AND STATS_GOAL_ASSISTED = 5 AND STATS_CLEAN_SHEET = 10 AND STATS_GAMES_PLAYED = 31));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 9 
                        AND STATS_GOAL_ASSISTED = 3 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 25));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 3));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 3 
                        AND STATS_GOAL_ASSISTED = 3 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 25));  
  
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 11 
                        AND STATS_GOAL_ASSISTED = 9 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 36));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 7 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 30));  


CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 9 AND STATS_GAMES_PLAYED = 25));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 2 
                        AND STATS_GOAL_ASSISTED = 1 AND STATS_CLEAN_SHEET = 13 AND STATS_GAMES_PLAYED = 34));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 2 AND STATS_CLEAN_SHEET = 1 AND STATS_GAMES_PLAYED = 8));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 3 AND STATS_GAMES_PLAYED = 11));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 3 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET IS NULL AND STATS_GAMES_PLAYED = 14));  

CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 0));  
 
CALL SP_PLAYERSEASON_ADD((SELECT SEASON_ID FROM SEASON WHERE SEASON_YEAR = 2020),
						(SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'),
                        (SELECT STATS_ID FROM STATS WHERE STATS_GOAL_SCORED = 0 
                        AND STATS_GOAL_ASSISTED = 0 AND STATS_CLEAN_SHEET = 0 AND STATS_GAMES_PLAYED = 0));  
  

-- Add Data to PLAYER_HISTORY Table
-- Used Subquery to find PLAYER_ID
CALL SP_PLAYERHISTORY_ADD(2014, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Phil'), NULL);
CALL SP_PLAYERHISTORY_ADD(2015, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'David'), NULL);
CALL SP_PLAYERHISTORY_ADD(2018, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Eric'), NULL);
CALL SP_PLAYERHISTORY_ADD(2016, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Paul'), NULL);
CALL SP_PLAYERHISTORY_ADD(2014, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Luke'), NULL);
CALL SP_PLAYERHISTORY_ADD(2014, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'), 2015);
CALL SP_PLAYERHISTORY_ADD(2020, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Dean'), NULL);
CALL SP_PLAYERHISTORY_ADD(2015, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Anthony'), NULL);
CALL SP_PLAYERHISTORY_ADD(2015, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Marcus'), NULL);
CALL SP_PLAYERHISTORY_ADD(2015, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Sergio'), NULL);
CALL SP_PLAYERHISTORY_ADD(2017, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Nemanja'), NULL);
CALL SP_PLAYERHISTORY_ADD(2017, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Scott'), NULL);
CALL SP_PLAYERHISTORY_ADD(2017, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Victor'), NULL);
CALL SP_PLAYERHISTORY_ADD(2018, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Fred'), NULL);
CALL SP_PLAYERHISTORY_ADD(2018, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Mason'), NULL);
CALL SP_PLAYERHISTORY_ADD(2019, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Brandon'), NULL);
CALL SP_PLAYERHISTORY_ADD(2019, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Aaron'), NULL);
CALL SP_PLAYERHISTORY_ADD(2019, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Harry'), NULL);
CALL SP_PLAYERHISTORY_ADD(2019, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Daniel'), NULL);
CALL SP_PLAYERHISTORY_ADD(2020, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Bruno'), NULL);
CALL SP_PLAYERHISTORY_ADD(2020, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Edinson'), NULL);
CALL SP_PLAYERHISTORY_ADD(2020, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Alex'), NULL);
CALL SP_PLAYERHISTORY_ADD(2017, (SELECT PLAYER_ID FROM PLAYER WHERE PLAYER_FIRST_NAME = 'Juan'), NULL);

END $$

DELIMITER ;

/*
	Create views for checking each tables
*/

DELIMITER $$
DROP PROCEDURE IF EXISTS SP_CREATE_VIEWS$$
CREATE PROCEDURE SP_CREATE_VIEWS()
BEGIN

/*
	Creating Views for SQL Queries
*/


-- Which players are transfer listed? (Which players the club wants to sell)
CREATE OR REPLACE VIEW VIEW_SELL_CENTER_BACK AS
	SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME
	FROM POSITIONS
		INNER JOIN PLAYERPOSITIONS ON POSITIONS.POSITIONS_ID = PLAYERPOSITIONS.POSITIONS_ID
		INNER JOIN PLAYER ON PLAYERPOSITIONS.PLAYER_ID = PLAYER.PLAYER_ID
		INNER JOIN TRANSFERLIST ON PLAYER.TRANSFERLIST_ID = TRANSFERLIST.TRANSFERLIST_ID
	WHERE 
		TRANSFERLIST_LISTED IS TRUE AND POSITIONS_PRIMARY = 'Center Back';

CREATE OR REPLACE VIEW VIEW_SELL_CENTER_MID AS    
	SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME
	FROM POSITIONS
		INNER JOIN PLAYERPOSITIONS ON POSITIONS.POSITIONS_ID = PLAYERPOSITIONS.POSITIONS_ID
		INNER JOIN PLAYER ON PLAYERPOSITIONS.PLAYER_ID = PLAYER.PLAYER_ID
		INNER JOIN TRANSFERLIST ON PLAYER.TRANSFERLIST_ID = TRANSFERLIST.TRANSFERLIST_ID
	WHERE 
		TRANSFERLIST_LISTED IS TRUE AND POSITIONS_PRIMARY = 'Center Midfield';

CREATE OR REPLACE VIEW VIEW_SELL_STRIKER AS		
	SELECT PLAYER_FIRST_NAME, PLAYER_LAST_NAME
	FROM POSITIONS
		INNER JOIN PLAYERPOSITIONS ON POSITIONS.POSITIONS_ID = PLAYERPOSITIONS.POSITIONS_ID
		INNER JOIN PLAYER ON PLAYERPOSITIONS.PLAYER_ID = PLAYER.PLAYER_ID
		INNER JOIN TRANSFERLIST ON PLAYER.TRANSFERLIST_ID = TRANSFERLIST.TRANSFERLIST_ID
	WHERE 
		TRANSFERLIST_LISTED IS TRUE AND POSITIONS_PRIMARY = 'Striker';


-- Stats for the players who were part of the club in the 2018 season
CREATE OR REPLACE VIEW VIEW_PLAYERS_STATS_2018 AS
	SELECT 
		PLAYER_FIRST_NAME,PLAYER_LAST_NAME, 
		STATS_GOAL_SCORED, STATS_GOAL_ASSISTED, 
		STATS_CLEAN_SHEET, STATS_GAMES_PLAYED
	FROM PLAYER
		INNER JOIN PLAYERSEASON ON PLAYER.PLAYER_ID = PLAYERSEASON.PLAYER_ID
		INNER JOIN SEASON ON PLAYERSEASON.SEASON_ID = SEASON.SEASON_ID
		INNER JOIN STATS ON PLAYERSEASON.STATS_ID = STATS.STATS_ID
	WHERE
		STATS.STATS_ID IS NOT NULL AND SEASON.SEASON_YEAR = '2018';

-- Stats for the players who were part of the club in the 2019 season
CREATE OR REPLACE VIEW VIEW_PLAYERS_STATS_2019 AS
	SELECT 
		PLAYER_FIRST_NAME,PLAYER_LAST_NAME,
		STATS_GOAL_SCORED, STATS_GOAL_ASSISTED, 
		STATS_CLEAN_SHEET, STATS_GAMES_PLAYED
	FROM PLAYER
		INNER JOIN PLAYERSEASON ON PLAYER.PLAYER_ID = PLAYERSEASON.PLAYER_ID
		INNER JOIN SEASON ON PLAYERSEASON.SEASON_ID = SEASON.SEASON_ID
		INNER JOIN STATS ON PLAYERSEASON.STATS_ID = STATS.STATS_ID
	WHERE
		STATS.STATS_ID IS NOT NULL AND SEASON.SEASON_YEAR = '2019';
    
-- Stats for the players who were part of the club in the 2020 season
CREATE OR REPLACE VIEW VIEW_PLAYERS_STATS_2020 AS
	SELECT 
		PLAYER_FIRST_NAME,PLAYER_LAST_NAME, 
		STATS_GOAL_SCORED, STATS_GOAL_ASSISTED, 
		STATS_CLEAN_SHEET, STATS_GAMES_PLAYED
	FROM PLAYER
		INNER JOIN PLAYERSEASON ON PLAYER.PLAYER_ID = PLAYERSEASON.PLAYER_ID
		INNER JOIN SEASON ON PLAYERSEASON.SEASON_ID = SEASON.SEASON_ID
		INNER JOIN STATS ON PLAYERSEASON.STATS_ID = STATS.STATS_ID
	WHERE
		STATS.STATS_ID IS NOT NULL AND SEASON.SEASON_YEAR = '2020';

-- Finding English players that won an award before
CREATE OR REPLACE VIEW VIEW_ENGLISH_AWARD_WON AS
	SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME
	FROM COUNTRY
		INNER JOIN PLAYER ON COUNTRY.COUNTRY_ID = PLAYER.COUNTRY_ID
		INNER JOIN PLAYERAWARD ON PLAYER.PLAYER_ID = PLAYERAWARD.PLAYER_ID
		INNER JOIN AWARD ON PLAYERAWARD.AWARD_ID = AWARD.AWARD_ID
	WHERE
		COUNTRY_NAME = 'England' AND AWARD_TITLE IS NOT NULL;

-- Finding players that have not won an award yet
CREATE OR REPLACE VIEW VIEW_PLAYERS_AWARD_NONE AS
	SELECT
		PLAYER_FIRST_NAME,PLAYER_LAST_NAME
	FROM AWARD
		LEFT OUTER JOIN PLAYERAWARD ON AWARD.AWARD_ID = PLAYERAWARD.AWARD_ID
		LEFT OUTER JOIN PLAYER ON PLAYERAWARD.PLAYER_ID = PLAYER.PLAYER_ID
	WHERE AWARD_TITLE IS NULL;
    
-- Create view for finding which player joined the club mulitiple times
CREATE OR REPLACE VIEW VIEW_PLAYER_JOIN_MUL AS
	SELECT PLAYER_FIRST_NAME, PLAYER_LAST_NAME, COUNT(PLAYER_HISTORY.PLAYER_ID)
	FROM PLAYER
		INNER JOIN PLAYER_HISTORY ON PLAYER.PLAYER_ID = PLAYER_HISTORY.PLAYER_ID
		INNER JOIN PLAYERPOSITIONS ON PLAYER.PLAYER_ID = PLAYERPOSITIONS.PLAYER_ID
		INNER JOIN POSITIONS ON PLAYERPOSITIONS.POSITIONS_ID = POSITIONS.POSITIONS_ID
	GROUP BY PLAYER_FIRST_NAME, PLAYER_LAST_NAME
	HAVING COUNT(PLAYER_HISTORY.PLAYER_ID) > 1;

-- Create view for one denormalization table. Tells important information about the players
CREATE OR REPLACE VIEW VIEW_PLAYER_INFO AS
	SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME, COUNTRY_NAME, 
				 TRANSFERLIST_LISTED, PLAYER_AGE, PLAYER_WEIGHT,
				 PLAYER_HEIGHT, PLAYER_JERSEY_NUMBER, PLAYER_MARKET_VALUE,
				 PLAYER_WAGE, POSITIONS_PRIMARY, SEASON_YEAR,
				 STATS_GOAL_SCORED, STATS_GOAL_ASSISTED, STATS_CLEAN_SHEET,
				 STATS_GAMES_PLAYED
	FROM PLAYER
		INNER JOIN PLAYERPOSITIONS ON PLAYER.PLAYER_ID = PLAYERPOSITIONS.PLAYER_ID
		INNER JOIN POSITIONS ON PLAYERPOSITIONS.POSITIONS_ID = POSITIONS.POSITIONS_ID
		INNER JOIN PLAYERSEASON ON PLAYER.PLAYER_ID = PLAYERSEASON.PLAYER_ID
		INNER JOIN SEASON ON PLAYERSEASON.SEASON_ID = SEASON.SEASON_ID
		INNER JOIN STATS ON PLAYERSEASON.STATS_ID = STATS.STATS_ID
		INNER JOIN COUNTRY ON PLAYER.COUNTRY_ID = COUNTRY.COUNTRY_ID
		INNER JOIN TRANSFERLIST ON PLAYER.TRANSFERLIST_ID = TRANSFERLIST.TRANSFERLIST_ID;

END $$

DELIMITER ;
/*
	Create Stored Procedure for creating data
*/

DELIMITER $$
DROP PROCEDURE IF EXISTS SP_CREATE_DATA$$
CREATE PROCEDURE SP_CREATE_DATA()
BEGIN
	CALL SP_DROP_TABLES();
    CALL SP_CREATE_TABLES();
    CALL SP_CREATE_VIEWS();
    CALL SP_POPULATE_DATA();
    
END $$

DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS SP_SHOW_RESULT$$
CREATE PROCEDURE SP_SHOW_RESULT()
BEGIN
/*
	View Interesting Queries
*/
-- Which players are transfer listed from specific positions? (Which players the club wants to sell)
	-- Center Backs
	SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_SELL_CENTER_BACK;
    
    -- Center Midfields
    SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_SELL_CENTER_MID;
    
    -- Strikers
    SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_SELL_STRIKER;

-- Stats for the players who were part of the club in the 2018 season
SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME', 
		STATS_GOAL_SCORED AS 'GOALS', STATS_GOAL_ASSISTED AS 'ASSISTS', 
		STATS_CLEAN_SHEET AS 'CLEAN SHEET', STATS_GAMES_PLAYED AS 'GAMES'
FROM VIEW_PLAYERS_STATS_2018;

-- Stats for the players who were part of the club in the 2019 season
SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME', 
		STATS_GOAL_SCORED AS 'GOALS', STATS_GOAL_ASSISTED AS 'ASSISTS', 
		STATS_CLEAN_SHEET AS 'CLEAN SHEET', STATS_GAMES_PLAYED AS 'GAMES'
FROM VIEW_PLAYERS_STATS_2019;

-- Stats for the players who were part of the club in the 2020 season
SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME', 
		STATS_GOAL_SCORED AS 'GOALS', STATS_GOAL_ASSISTED AS 'ASSISTS', 
		STATS_CLEAN_SHEET AS 'CLEAN SHEET', STATS_GAMES_PLAYED AS 'GAMES'
FROM VIEW_PLAYERS_STATS_2020;

-- Finding English players that won an award before
SELECT DISTINCT CONCAT(PLAYER_FIRST_NAME,' ',PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_ENGLISH_AWARD_WON;

-- Finding players that have not won an award yet
SELECT CONCAT(PLAYER_FIRST_NAME,' ',PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_PLAYERS_AWARD_NONE;

-- Finding which player joined the club multiple time
SELECT CONCAT(PLAYER_FIRST_NAME,' ', PLAYER_LAST_NAME) AS 'PLAYER NAME' FROM VIEW_PLAYER_JOIN_MUL;


/*
	Denormalizing Tables
*/
-- Show most important information about the players
SELECT CONCAT(PLAYER_FIRST_NAME,' ',PLAYER_LAST_NAME) AS 'Name', COUNTRY_NAME AS 'Nationality', 
				 TRANSFERLIST_LISTED AS 'Transfer Status', PLAYER_AGE AS 'Age', PLAYER_WEIGHT AS 'Weight',
				 PLAYER_HEIGHT AS 'Height', PLAYER_JERSEY_NUMBER AS 'Jersey Number', PLAYER_MARKET_VALUE AS 'Market Value',
				 PLAYER_WAGE AS 'Wage', POSITIONS_PRIMARY AS 'Position', SEASON_YEAR AS 'Season',
				 STATS_GOAL_SCORED AS 'Goals', STATS_GOAL_ASSISTED AS 'Assists', STATS_CLEAN_SHEET AS 'Clean Sheets',
				 STATS_GAMES_PLAYED AS 'Total Games'
FROM VIEW_PLAYER_INFO;

END $$ 

DELIMITER ;


/*
	Final Result
*/

CALL SP_CREATE_DATA();
CALL SP_SHOW_RESULT();


